# Generated by Django 3.2.3 on 2021-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image_link', models.TextField()),
                ('desc_short', models.CharField(max_length=200)),
                ('desc_long', models.TextField()),
                ('is_proper', models.BooleanField()),
                ('datetime', models.CharField(max_length=120)),
            ],
        ),
    ]
